FROM dhi.io/valkey:9.1.0-debian13-dev@sha256:f199131cf2f022eeba9731572ab0fe1413a10609cb5e24d9ea5c9dec1615deb3

USER 0
RUN apt-get update && apt-get install -y --no-install-recommends passwd \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd --gid 999 valkey \
    && useradd --uid 999 --gid 999 --comment "Valkey Database Server" \
        --home-dir /var/lib/redis --shell /usr/sbin/nologin --create-home valkey \
    && ln -sf /usr/local/bin/valkey-server /usr/local/bin/redis-server \
    && ln -sf /usr/local/bin/valkey-cli /usr/local/bin/redis-cli
