FROM dhi.io/postgres:15.19-debian13-dev@sha256:43481d0c7681108be78ef015fa548237a818421d80f7ba4ce8e63ddad7474f93 AS pg15

FROM dhi.io/postgres:18.6-debian13-dev@sha256:890cb7b12cf5064455c7a9830c1a9e02517d038349c577418b417c0e7c7ca06b

ENV PGDATA=/var/lib/postgresql/data

USER 0
RUN apt-get update && apt-get install -y --no-install-recommends bc findutils gzip passwd util-linux \
    && rm -rf /var/lib/apt/lists/* \
    && groupmod --gid 999 postgres \
    && usermod --uid 999 --gid 999 postgres \
    && mkdir -p /docker-entrypoint-initdb.d /run/postgresql "$PGDATA" \
    && chown -R postgres:postgres /run/postgresql /var/lib/postgresql \
    && chmod 2777 /run/postgresql \
    && chmod 777 "$PGDATA"

COPY --from=pg15 /opt/postgresql/15 /opt/postgresql/15
