FROM dhi.io/postgres:15.18-debian13-dev@sha256:b0fe2d7f82d746fec877874f4ac4d3e333b1fff011a9cc1e47cba2cfca5f8da8 AS pg15

FROM dhi.io/postgres:18.4-debian13-dev@sha256:7360ad8ea76a078cdf42aebc184def993c465af34200d4c88a134fb7bc32e59c

ENV PGDATA=/var/lib/postgresql/data

USER 0
RUN apt-get update && apt-get install -y --no-install-recommends bc findutils gzip passwd util-linux \
    && rm -rf /var/lib/apt/lists/* \
    && groupmod --gid 999 postgres \
    && usermod --uid 999 --gid 999 postgres \
    && mkdir -p /docker-entrypoint-initdb.d /run/postgresql "$PGDATA" \
    && chown -R postgres:postgres /run/postgresql /var/lib/postgresql \
    && chmod 2777 /run/postgresql \
    && chmod 777 "$PGDATA"

COPY --from=pg15 /opt/postgresql/15 /opt/postgresql/15
