# DHI Debian-based API test image
FROM dhi.io/debian-base:trixie-debian13-dev@sha256:5c45913e72c90581fc4cca57c3a7cd7dcac2d9fa44fce24fe4cfa342e5ccb7a6
ENV LANG=C.UTF-8
ENV HELM_EXPERIMENTAL_OCI=1
ENV COSIGN_PASSWORD=Harbor12345
ENV COSIGN_EXPERIMENTAL=1
ENV COSIGN_OCI_EXPERIMENTAL=1
ENV NOTATION_EXPERIMENTAL=1

RUN mkdir -p /usr/local/bin
COPY --from=tool_builder /tool/tools.tar.gz /usr/local/bin

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    curl \
    git \
    default-jdk-headless \
    iproute2 \
    iptables \
    build-essential \
    sed \
    libssl-dev \
    tar \
    procps \
    gzip \
    python3 \
    python3-pip \
    python3-setuptools \
    libnss3-tools \
    podman \
    && pip3 install --break-system-packages --upgrade pip pyasn1 google-apitools==0.5.31 gsutil python-dateutil \
    robotframework==6.0.1 robotframework-sshlibrary robotframework-httplibrary \
    requests dbbot robotframework-seleniumlibrary robotframework-pabot \
    robotframework-JSONLibrary hurry.filesize --upgrade && \
    rm -rf /var/lib/apt/lists/*

RUN pwd && ls && \
    # Install docker
    DOCKER_VERSION=20.10.3 && wget https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_VERSION.tgz && \
    tar --strip-components=1 -xvzf docker-$DOCKER_VERSION.tgz -C /usr/bin &&  \
    rm docker-$DOCKER_VERSION.tgz

COPY containerd_config.toml /etc/containerd/config.toml
COPY busybox.tar /
# This container needs to be run in privileged mode(run with --privileged option) to make it work
COPY dockerd-entrypoint.sh /usr/local/bin/dockerd-entrypoint.sh

RUN chmod +x /usr/local/bin/dockerd-entrypoint.sh && \
    mkdir -p $HOME/.pki/nssdb && \
    echo Harbor12345 > password.ca && \
    certutil -d sql:$HOME/.pki/nssdb -N -f password.ca

VOLUME /var/lib/docker
