FROM dhi.io/nginx:1.31.3-debian13-dev@sha256:c0f34463d05737646ba965de939e228e6af7a90b4d84ceba3d5634e70740df45

RUN apt-get update && apt-get install -y --no-install-recommends curl passwd \
    && rm -rf /var/lib/apt/lists/* \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log \
    && groupmod --gid 10000 nginx && usermod --gid 10000 --uid 10000 --home /home/nginx --shell /bin/bash nginx \
    && chown -R nginx:nginx /etc/nginx
